/**
 * process-order.js — Netlify serverless function
 *
 * Receives a payment token + order details from the browser, charges the
 * card via Square's Payments API, and creates a matching Order in Square
 * so it shows up in the POS.
 *
 * ENVIRONMENT VARIABLES required (set in Netlify dashboard, NOT in code):
 *   SQUARE_ACCESS_TOKEN — the secret. Sandbox token for testing, production
 *                        token when going live.
 *   SQUARE_ENVIRONMENT  — "sandbox" or "production"
 *   SQUARE_LOCATION_ID  — Cortez location ID
 *
 * The browser never sees the access token. The browser ONLY sees the
 * Application ID + Location ID (public-ish) plus a one-time payment nonce
 * generated by Square's Web Payments SDK.
 */

const { Client, Environment } = require('square');
const crypto = require('crypto');

// Helper: format USD cents from a dollar amount string or number
function toCents(amount) {
  if (typeof amount === 'string') amount = parseFloat(amount);
  if (!isFinite(amount) || amount < 0) return 0;
  return Math.round(amount * 100);
}

// Helper: build a clean JSON response.
// CORS is locked to the site's own origin — the checkout runs same-origin, so
// nothing else legitimately calls this from a browser.
function json(statusCode, body) {
  return {
    statusCode,
    headers: {
      'Content-Type': 'application/json',
      'Access-Control-Allow-Origin': 'https://wiredcoffee.org',
      'Access-Control-Allow-Headers': 'Content-Type',
      'Access-Control-Allow-Methods': 'POST, OPTIONS'
    },
    body: JSON.stringify(body)
  };
}

// Server-side floor prices (12oz / smallest size, in dollars) for every named
// item the site can send. The client's unitPrice arrives already member-
// discounted (x0.9 at most), so an item is rejected if it prices below
// 90% of its floor. Custom builder / invented drinks are not in this list and
// fall back to the $2 house floor. Never trust the client's arithmetic.
const FLOOR_PRICES = {
  'nutty professor': 5, 'maple byte': 5, 'flow state': 5, 'prickly palmer': 5,
  'house brew': 3, 'cold brew': 4, 'latte': 4, 'mocha': 4, 'breve': 4.5,
  'americano': 3.5, 'cappuccino': 4, 'cortado': 4, 'espresso': 2,
  'tea': 2, 'navajo tea': 2, 'green tea': 2, 'black tea': 2,
  'herbal lemon': 2, 'herbal peppermint': 2, 'matcha': 4, 'chai': 4,
  'lemonade': 2.5, 'prickly pear lemonade': 2.5, 'soda': 2.5, 'rize fuel energy': 2.5,
  'circuit berry smoothie': 5.5, 'maker mango smoothie': 5.5, 'pink prototype smoothie': 5.5,
  'peach paradise smoothie': 5.5, 'green machine smoothie': 5.5, 'java jolt smoothie': 6,
  'circuit berry': 5.5, 'maker mango': 5.5, 'pink prototype': 5.5,
  'peach paradise': 5.5, 'green machine': 5.5, 'java jolt': 6,
  'cheese': 3.5, 'pepperoni': 4, 'specialty': 5,
  'bagel & cream cheese': 3.5, 'breakfast bagel': 6.5,
  'double chocolate espresso cookie': 3, 'chocolate chip cookie': 3,
  "maker's lunch": 10, 'jump start': 8, 'quick byte': 5,
  'dark circuit': 7, 'the kernel': 6, 'black box': 6, 'burnt signal': 5,
  'white noise': 8, 'honeycomb': 7, 'caramel cache': 7, 'golden hour': 8,
  'green volt': 7, 'chai charge': 7, 'nut cluster': 8, 'cinnamon toast': 8,
  'vanilla sky': 8, 'root access': 8, 'cold circuit': 8, 'static': 4
};
function floorFor(name) {
  const n = String(name || '').toLowerCase().replace(/^the /, '').replace(/’/g, "'").trim();
  return FLOOR_PRICES[n] != null ? FLOOR_PRICES[n] : 2;
}

// Square Loyalty accrual for a paid order. Custom checkouts do not accrue
// automatically, so after a completed payment we look up (or create) the
// loyalty account by phone and accumulate points for the order. Every failure
// here is swallowed: loyalty must never break a paid order.
async function accrueLoyalty(client, locationId, orderId, phoneRaw) {
  const digits = String(phoneRaw || '').replace(/\D/g, '');
  if (digits.length < 10) return null;
  const phone = '+1' + digits.slice(-10);

  const progRes = await client.loyaltyApi.retrieveLoyaltyProgram('main');
  const program = progRes.result && progRes.result.program;
  if (!program || program.status !== 'ACTIVE') return null;

  const searchRes = await client.loyaltyApi.searchLoyaltyAccounts({
    query: { mappings: [{ phoneNumber: phone }] }, limit: 1
  });
  let account = searchRes.result && searchRes.result.loyaltyAccounts && searchRes.result.loyaltyAccounts[0];
  if (!account) {
    const createRes = await client.loyaltyApi.createLoyaltyAccount({
      idempotencyKey: 'loy-' + orderId,
      loyaltyAccount: { programId: program.id, mapping: { phoneNumber: phone } }
    });
    account = createRes.result && createRes.result.loyaltyAccount;
  }
  if (!account || !account.id) return null;

  const accRes = await client.loyaltyApi.accumulateLoyaltyPoints(account.id, {
    idempotencyKey: 'acc-' + orderId,
    accumulatePoints: { orderId: orderId },
    locationId: locationId
  });
  let pts = 0;
  ((accRes.result && accRes.result.events) || []).forEach(function (e) {
    if (e.accumulatePoints && e.accumulatePoints.points) pts += Number(e.accumulatePoints.points);
  });
  const prior = Number(account.balance || 0);
  const term = program.terminology || {};
  return { points: pts, balance: prior + pts, unit: pts === 1 ? (term.one || 'point') : (term.other || 'points') };
}

exports.handler = async function(event) {
  // CORS preflight
  if (event.httpMethod === 'OPTIONS') return json(200, {});
  if (event.httpMethod !== 'POST') return json(405, { error: 'Method not allowed' });

  // Validate required env vars
  const accessToken = process.env.SQUARE_ACCESS_TOKEN;
  const environment = (process.env.SQUARE_ENVIRONMENT || 'sandbox').trim().toLowerCase();
  const locationId  = process.env.SQUARE_LOCATION_ID;
  if (!accessToken || !locationId) {
    console.error('Missing env vars', { hasToken: !!accessToken, hasLocation: !!locationId });
    return json(500, { error: 'Server is not configured. Contact the shop.' });
  }

  // Parse + validate the incoming order
  let payload;
  try {
    payload = JSON.parse(event.body || '{}');
  } catch (e) {
    return json(400, { error: 'Invalid request body' });
  }

  // TEMPORARY connection diagnostic: reports which environment the function
  // runs against and which locations the token can see. No secrets returned.
  // Remove after the Square connection is confirmed.
  if (payload.diag === true) {
    const diagClient = new Client({
      accessToken: accessToken,
      environment: environment === 'production' ? Environment.Production : Environment.Sandbox
    });
    const out = {
      environmentVar: process.env.SQUARE_ENVIRONMENT || '(unset, defaulting to sandbox)',
      usingBase: environment === 'production' ? 'production' : 'sandbox',
      tokenLength: accessToken.length,
      configuredLocation: locationId
    };
    try {
      const locRes = await diagClient.locationsApi.listLocations();
      out.tokenWorks = true;
      out.locationsVisible = (locRes.result.locations || []).map(function (l) {
        return l.id + ' (' + (l.name || '') + ', ' + (l.status || '') + ')';
      });
      out.configuredLocationVisible = (locRes.result.locations || []).some(function (l) { return l.id === locationId; });
    } catch (e) {
      out.tokenWorks = false;
      out.squareError = (e && e.errors && e.errors[0]) || (e && e.message) || 'unknown';
    }
    return json(200, out);
  }

  const {
    sourceId,          // payment token from Square Web Payments SDK
    customerName,      // customer's name
    customerPhone,     // customer's phone (digits only or with formatting)
    items,             // array of { name, variant, qty, unitPrice, modifiers: [{name, price}] }
    tipAmount,         // dollars, e.g. "1.50"
    subtotalCheck      // dollars, what the browser thinks the subtotal is — we recompute server-side
  } = payload;

  if (!sourceId) return json(400, { error: 'Missing payment information' });
  if (!customerName || !customerName.trim()) return json(400, { error: 'Name is required' });
  if (!customerPhone || customerPhone.replace(/\D/g, '').length < 10) {
    return json(400, { error: 'A valid phone number is required' });
  }
  if (!Array.isArray(items) || items.length === 0) {
    return json(400, { error: 'Cart is empty' });
  }

  // Recompute subtotal server-side from the items array — never trust the client
  let subtotalCents = 0;
  const lineItems = [];
  for (const item of items) {
    const qty = parseInt(item.qty, 10) || 1;
    if (qty < 1 || qty > 20) {
      return json(400, { error: 'Invalid quantity for ' + (item.name || 'item') });
    }
    const baseCents = toCents(item.unitPrice);
    let modsCents = 0;
    const modNames = [];
    if (Array.isArray(item.modifiers)) {
      for (const m of item.modifiers) {
        modsCents += toCents(m.price);
        if (m.name) modNames.push(m.name);
      }
    }
    // Price-floor check: reject any line priced below 90% (max member
    // discount) of the item's known smallest-size price, minus a penny of
    // float slack. Upward is allowed (sizes, shots, syrups add cost).
    const unitCents = baseCents + modsCents;
    const floorCents = Math.round(floorFor(item.name) * 100 * 0.9) - 1;
    if (unitCents < floorCents) {
      console.warn('Price floor rejection', { name: item.name, unitCents, floorCents });
      return json(400, { error: 'Price check failed for ' + (item.name || 'an item') + '. Refresh the page and try again.' });
    }
    if (unitCents > 2500) {
      return json(400, { error: 'Item price out of range for ' + (item.name || 'an item') });
    }

    const lineCents = unitCents * qty;
    subtotalCents += lineCents;

    // Build a Square line item — using ad-hoc items rather than catalog references
    // so the menu can be edited in admin without re-syncing to Square's catalog.
    const lineNameParts = [];
    if (item.variant) lineNameParts.push(item.variant);
    lineNameParts.push(item.name || 'Item');
    const lineName = lineNameParts.join(' ');
    const note = modNames.length ? modNames.join(', ') : undefined;

    lineItems.push({
      name: lineName.slice(0, 500),
      quantity: String(qty),
      basePriceMoney: { amount: BigInt(baseCents + modsCents), currency: 'USD' },
      ...(note ? { note: note.slice(0, 500) } : {})
    });
  }

  const tipCents = toCents(tipAmount);
  const totalCents = subtotalCents + tipCents;

  if (totalCents < 100) {
    return json(400, { error: 'Order total must be at least $1.00' });
  }
  if (totalCents > 50000) {
    return json(400, { error: 'Order total exceeds $500 — please call the shop' });
  }

  // Optional: sanity-check that client and server agree on subtotal (just for logging)
  if (subtotalCheck) {
    const clientCents = toCents(subtotalCheck);
    if (Math.abs(clientCents - subtotalCents) > 1) {
      console.warn('Subtotal mismatch', { clientCents, subtotalCents });
    }
  }

  // Initialize Square client
  const client = new Client({
    accessToken: accessToken,
    environment: environment === 'production' ? Environment.Production : Environment.Sandbox
  });

  const idempotencyKey = crypto.randomUUID();

  // If the card is declined after the order is created, cancel the order so it
  // never shows on the POS as a ghost pickup ticket.
  async function cancelOrder(order) {
    if (!order || !order.id) return;
    try {
      await client.ordersApi.updateOrder(order.id, {
        idempotencyKey: 'cancel-' + idempotencyKey,
        order: { locationId, version: order.version, state: 'CANCELED' }
      });
    } catch (e) {
      console.error('Failed to cancel order after payment failure', order.id, e && e.errors ? e.errors : e);
    }
  }

  let createdOrder = null;
  try {
    // Create the order first — itemized for the receipt + POS
    const orderRes = await client.ordersApi.createOrder({
      idempotencyKey: 'order-' + idempotencyKey,
      order: {
        locationId,
        lineItems,
        state: 'OPEN',
        source: { name: 'Wired Coffee Co. — Online' },
        fulfillments: [{
          type: 'PICKUP',
          state: 'PROPOSED',
          pickupDetails: {
            recipient: { displayName: customerName.slice(0, 100), phoneNumber: customerPhone.slice(0, 30) },
            scheduleType: 'ASAP',
            pickupAt: new Date(Date.now() + 10 * 60 * 1000).toISOString()
          }
        }],
        ...(tipCents > 0 ? {
          serviceCharges: [{
            name: 'Tip',
            amountMoney: { amount: BigInt(tipCents), currency: 'USD' },
            calculationPhase: 'TOTAL_PHASE',
            taxable: false
          }]
        } : {})
      }
    });

    const order = orderRes.result && orderRes.result.order;
    if (!order || !order.id) {
      console.error('Order creation returned no order', orderRes);
      return json(500, { error: 'Failed to create order. Try again or call the shop.' });
    }
    createdOrder = order;

    // Now charge the card, attaching the order so the payment lands on it
    const paymentRes = await client.paymentsApi.createPayment({
      sourceId,
      idempotencyKey: 'pay-' + idempotencyKey,
      amountMoney: { amount: BigInt(totalCents), currency: 'USD' },
      orderId: order.id,
      locationId,
      buyerEmailAddress: undefined,
      note: 'Online order — ' + customerName.slice(0, 60),
      autocomplete: true
    });

    const payment = paymentRes.result && paymentRes.result.payment;
    if (!payment || payment.status !== 'COMPLETED') {
      console.error('Payment did not complete', payment);
      await cancelOrder(createdOrder);
      return json(402, { error: 'Payment was declined. Try a different card.' });
    }

    // Loyalty accrual, opt-in from the checkout checkbox. Non-fatal.
    let loyalty = null;
    if (payload.loyalty === true) {
      try {
        loyalty = await accrueLoyalty(client, locationId, order.id, customerPhone);
      } catch (e) {
        console.error('Loyalty accrual failed (order is fine)', e && e.errors ? e.errors : e);
      }
    }

    return json(200, {
      ok: true,
      orderId: order.id,
      paymentId: payment.id,
      receiptUrl: payment.receiptUrl || null,
      totalDollars: (totalCents / 100).toFixed(2),
      loyalty: loyalty
    });
  } catch (err) {
    console.error('Square API error', err && err.errors ? err.errors : err);
    await cancelOrder(createdOrder);
    // Surface a clean message but never leak token / internals
    const safeMessage = (err && err.errors && err.errors[0] && err.errors[0].detail) ||
                        (err && err.message) ||
                        'Unknown error';
    if (/CARD_DECLINED|GENERIC_DECLINE|CVV_FAILURE|INSUFFICIENT_FUNDS|PAN_FAILURE|INVALID_EXPIRATION/i.test(safeMessage)) {
      return json(402, { error: 'Card declined — try a different card.' });
    }
    return json(500, { error: 'Order failed: ' + safeMessage });
  }
};
