/**
 * process-order.js — Netlify serverless function
 *
 * Receives a payment token + order details from the browser, charges the
 * card via Square's Payments API, and creates a matching Order in Square
 * so it shows up in the POS.
 *
 * ENVIRONMENT VARIABLES required (set in Netlify dashboard, NOT in code):
 *   SQUARE_ACCESS_TOKEN — the secret. Sandbox token for testing, production
 *                        token when going live.
 *   SQUARE_ENVIRONMENT  — "sandbox" or "production"
 *   SQUARE_LOCATION_ID  — Cortez location ID
 *
 * The browser never sees the access token. The browser ONLY sees the
 * Application ID + Location ID (public-ish) plus a one-time payment nonce
 * generated by Square's Web Payments SDK.
 */

const { Client, Environment } = require('square');
const crypto = require('crypto');

// Helper: format USD cents from a dollar amount string or number
function toCents(amount) {
  if (typeof amount === 'string') amount = parseFloat(amount);
  if (!isFinite(amount) || amount < 0) return 0;
  return Math.round(amount * 100);
}

// Helper: build a clean JSON response
function json(statusCode, body) {
  return {
    statusCode,
    headers: {
      'Content-Type': 'application/json',
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Headers': 'Content-Type',
      'Access-Control-Allow-Methods': 'POST, OPTIONS'
    },
    body: JSON.stringify(body)
  };
}

exports.handler = async function(event) {
  // CORS preflight
  if (event.httpMethod === 'OPTIONS') return json(200, {});
  if (event.httpMethod !== 'POST') return json(405, { error: 'Method not allowed' });

  // Validate required env vars
  const accessToken = process.env.SQUARE_ACCESS_TOKEN;
  const environment = process.env.SQUARE_ENVIRONMENT || 'sandbox';
  const locationId  = process.env.SQUARE_LOCATION_ID;
  if (!accessToken || !locationId) {
    console.error('Missing env vars', { hasToken: !!accessToken, hasLocation: !!locationId });
    return json(500, { error: 'Server is not configured. Contact the shop.' });
  }

  // Parse + validate the incoming order
  let payload;
  try {
    payload = JSON.parse(event.body || '{}');
  } catch (e) {
    return json(400, { error: 'Invalid request body' });
  }

  const {
    sourceId,          // payment token from Square Web Payments SDK
    customerName,      // customer's name
    customerPhone,     // customer's phone (digits only or with formatting)
    items,             // array of { name, variant, qty, unitPrice, modifiers: [{name, price}] }
    tipAmount,         // dollars, e.g. "1.50"
    subtotalCheck      // dollars, what the browser thinks the subtotal is — we recompute server-side
  } = payload;

  if (!sourceId) return json(400, { error: 'Missing payment information' });
  if (!customerName || !customerName.trim()) return json(400, { error: 'Name is required' });
  if (!customerPhone || customerPhone.replace(/\D/g, '').length < 10) {
    return json(400, { error: 'A valid phone number is required' });
  }
  if (!Array.isArray(items) || items.length === 0) {
    return json(400, { error: 'Cart is empty' });
  }

  // Recompute subtotal server-side from the items array — never trust the client
  let subtotalCents = 0;
  const lineItems = [];
  for (const item of items) {
    const qty = parseInt(item.qty, 10) || 1;
    if (qty < 1 || qty > 20) {
      return json(400, { error: 'Invalid quantity for ' + (item.name || 'item') });
    }
    const baseCents = toCents(item.unitPrice);
    let modsCents = 0;
    const modNames = [];
    if (Array.isArray(item.modifiers)) {
      for (const m of item.modifiers) {
        modsCents += toCents(m.price);
        if (m.name) modNames.push(m.name);
      }
    }
    const lineCents = (baseCents + modsCents) * qty;
    subtotalCents += lineCents;

    // Build a Square line item — using ad-hoc items rather than catalog references
    // so the menu can be edited in admin without re-syncing to Square's catalog.
    const lineNameParts = [];
    if (item.variant) lineNameParts.push(item.variant);
    lineNameParts.push(item.name || 'Item');
    const lineName = lineNameParts.join(' ');
    const note = modNames.length ? modNames.join(', ') : undefined;

    lineItems.push({
      name: lineName.slice(0, 500),
      quantity: String(qty),
      basePriceMoney: { amount: BigInt(baseCents + modsCents), currency: 'USD' },
      ...(note ? { note: note.slice(0, 500) } : {})
    });
  }

  const tipCents = toCents(tipAmount);
  const totalCents = subtotalCents + tipCents;

  if (totalCents < 100) {
    return json(400, { error: 'Order total must be at least $1.00' });
  }
  if (totalCents > 50000) {
    return json(400, { error: 'Order total exceeds $500 — please call the shop' });
  }

  // Optional: sanity-check that client and server agree on subtotal (just for logging)
  if (subtotalCheck) {
    const clientCents = toCents(subtotalCheck);
    if (Math.abs(clientCents - subtotalCents) > 1) {
      console.warn('Subtotal mismatch', { clientCents, subtotalCents });
    }
  }

  // Initialize Square client
  const client = new Client({
    accessToken: accessToken,
    environment: environment === 'production' ? Environment.Production : Environment.Sandbox
  });

  const idempotencyKey = crypto.randomUUID();

  try {
    // Create the order first — itemized for the receipt + POS
    const orderRes = await client.ordersApi.createOrder({
      idempotencyKey: 'order-' + idempotencyKey,
      order: {
        locationId,
        lineItems,
        state: 'OPEN',
        source: { name: 'Wired Coffee Co. — Online' },
        fulfillments: [{
          type: 'PICKUP',
          state: 'PROPOSED',
          pickupDetails: {
            recipient: { displayName: customerName.slice(0, 100), phoneNumber: customerPhone.slice(0, 30) },
            scheduleType: 'ASAP',
            pickupAt: new Date(Date.now() + 10 * 60 * 1000).toISOString()
          }
        }],
        ...(tipCents > 0 ? {
          serviceCharges: [{
            name: 'Tip',
            amountMoney: { amount: BigInt(tipCents), currency: 'USD' },
            calculationPhase: 'TOTAL_PHASE',
            taxable: false
          }]
        } : {})
      }
    });

    const order = orderRes.result && orderRes.result.order;
    if (!order || !order.id) {
      console.error('Order creation returned no order', orderRes);
      return json(500, { error: 'Failed to create order. Try again or call the shop.' });
    }

    // Now charge the card, attaching the order so the payment lands on it
    const paymentRes = await client.paymentsApi.createPayment({
      sourceId,
      idempotencyKey: 'pay-' + idempotencyKey,
      amountMoney: { amount: BigInt(totalCents), currency: 'USD' },
      orderId: order.id,
      locationId,
      buyerEmailAddress: undefined,
      note: 'Online order — ' + customerName.slice(0, 60),
      autocomplete: true
    });

    const payment = paymentRes.result && paymentRes.result.payment;
    if (!payment || payment.status !== 'COMPLETED') {
      console.error('Payment did not complete', payment);
      return json(402, { error: 'Payment was declined. Try a different card.' });
    }

    return json(200, {
      ok: true,
      orderId: order.id,
      paymentId: payment.id,
      receiptUrl: payment.receiptUrl || null,
      totalDollars: (totalCents / 100).toFixed(2)
    });
  } catch (err) {
    console.error('Square API error', err && err.errors ? err.errors : err);
    // Surface a clean message but never leak token / internals
    const safeMessage = (err && err.errors && err.errors[0] && err.errors[0].detail) ||
                        (err && err.message) ||
                        'Unknown error';
    if (/CARD_DECLINED|GENERIC_DECLINE|CVV_FAILURE|INSUFFICIENT_FUNDS|PAN_FAILURE|INVALID_EXPIRATION/i.test(safeMessage)) {
      return json(402, { error: 'Card declined — try a different card.' });
    }
    return json(500, { error: 'Order failed: ' + safeMessage });
  }
};
